### ISSUE TITLE
Add Stock Plan Holdings to Stakeholder Snapshot Sheet

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#17]
_This task _DOES NOT_ include the "Options Remaining for Issuance" row yet which is documented in #18._

## Scope
From https://github.com/captable/ocx/files/11265982/OCX.v.0.4.xlsx
![image](https://user-images.githubusercontent.com/122016/232927946-3c944125-d1b9-4fff-a1b1-f86b49802d06.png)

## Desired outcome
- There should be one column for each STOCK_PLAN in the OCF package, even if the STOCK_PLAN has no associated transactions.
- The left-to-right column ordering places Stock Plans _to the right_ of Stock Classes. If there are multiple Stock Plans, they should be ordered from oldest STOCK_PLAN.board_approval_date to most recent, with nulls last, and name as tie-breaker.

## To-Do
- [x] Determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval
- [x] ocf-package: Are the necessary OCF Files being processed?
- [x] model: Are the necessary OCF Objects being consumed?
- [x] Develop workbook against Model interfaces.
- [x] Implement actual Model
- [x] Integrate and test end-to-end
