### ISSUE TITLE
Use OCF-specified rounding method for "as-converted" holdings columns

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#21]
## Scope
On the Stakeholder Snapshot sheet, with "Show Formulas" on:
![image](https://user-images.githubusercontent.com/122016/233469515-046f9868-6871-4fc8-af64-1591a1432a43.png)

In v0.4 of the OCX sample spreadsheet, the "as converted" columns use a single numeric value from the Context sheet to calculate outstanding shares on the Stakeholder Snapshot sheet. This, however, does not take into account the rounding method associated with the conversion ratio.

![image](https://user-images.githubusercontent.com/122016/233469751-a892fbfe-5408-4f8d-a76b-20078d5ee2c9.png)

## Desired outcome
The function used in these cells needs to correspond to the actual `rounding_type` in the OCF data.

## To-Do
- [x] If necessary, determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval, if necessary
- [x] ocf-package: Are the necessary OCF Files being processed?
- [ ] model: Are the necessary OCF Objects being consumed?
- [ ] Develop workbook against Model interfaces.
- [ ] Implement actual Model
- [ ] Integrate and test end-to-end
