### ISSUE TITLE
Handle multiple Stock Class Conversion Rights for preferred stock classes

### ISSUE THREAD

**Issue by pjohnmeyer** [captable/ocx#22]
In v0.4 of the OCX sample spreadsheet, the conversion ratio for a stock class appears on the Context sheet, which is used on the Stakeholder Snapshot sheet to calculated "as converted" numbers.

In v1.0.0 of the OCF specification, however, every stock class can have more than one possible "StockClassConversionRight", each of which can have its own separate ratio. Note that this is a list:

![image](https://user-images.githubusercontent.com/122016/233473753-6cedb4fc-89cc-470d-997c-193658b9687a.png)

## Desired Outcome
Per discussion with members of the Law Firm Working Group, the "normal" case is that each Preferred Stock Class will convert to a particular Common Stock Class with 1 vote per share as the "underlying" instrument for everything. There are other arrangements, of course, so we agreed the algorithm should be something like this:

1. If only one StockClassConversionRight converts to a common stock class, use that one's ratio
2. If more than one StockClassConversionRight converts to different common stock classes, choose the conversion ratio that corresponds with the common stock class with the _lowest non-zero_ votes per share.
3. If there are no conversions to common, but there are conversion to _another_ preferred stock class, recursively continue to apply steps 1 and 2 until a single common stock class is found -- multiplying all of the multipliers along the way.
4. ERROR otherwise

These rules only apply, however, if the StockClassConversionRight `converts_to_stock_class_id` -- if it `converts_to_future_round` we have no information on the target class. Classes that `converts_to_future_round` can have a ratio with no target common or preferred class to implement this against, so there are more questions to answer here -- or improvements to be made to OCF.

## To-Do
- [ ] If necessary, determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval, if necessary
- [ ] ocf-package: Are the necessary OCF Files being processed?
- [ ] model: Are the necessary OCF Objects being consumed?
- [ ] Develop workbook against Model interfaces.
- [ ] Implement actual Model
- [ ] Integrate and test end-to-end

**Comment by JSv4** [comment]
Thanks for this super thoughtful question @pjohnmeyer. 

Our initial take is, starting with given series of preferred stock, you'd want to recursively traverse the tree to the lowest non-zero common class / series it can convert into (with the caveat that this is a heuristic and the important thing here is to document the rules and show your work (as you noted). So, given Preferred A, we think you'd want to convert into Common Z. If, however, you started with Preferred D, then you'd want to find your way to Common X. Would be good to hear from others on this.

**Comment by daviidy** [comment]
To summarize, here are the different case scenarios we can work against:

- `converts_to_stock_class_id` is null
- `converts_to_future_round` is true (it raises questions like: can converts_to_stock_class_id and converts_to_future_round be null simultaneously? which property has the highest priority?)
- we have one StockClassConversionRight that converts to a common stock class
- we have 2 or more StockClassConversionRights that convert to different common stock classes
- we have 2 or more StockClassConversionRights that convert to different common and preferred stock classes

cc @pjohnmeyer

**Comment by pjohnmeyer** [comment]
Sounds like a good progression. I think on some of this we can make some assumptions, as long as we "show our work" as John says. So some thoughts:

For the purposes of calculating a ratio, this algorithm only cares about `converts_to_stock_class_id`, so it should take precedence. @JSv4 I added [this note to the wiki](https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/wiki/Planned-2.0-Rework#dont-allow-converts_to_stock_class_id-and-converts_to_future_round-true-on-the-same-conversion-right) but I didn't create an issue yet.

If there are no conversion pathways that reach an actual common stock then we can error out and not handle that case.

We will ultimately also want code for generating a text description of the conversion so we can add that to the "Notes" on the spreadsheet -- for now we could just Log it -- explaining the conversion, e.g. using John's two examples.

> Converted from Preferred A > Preferred B > Preferred C > Common Z at 8.0000

or

> Converted from Preferred D > Common X at 1.5000

The full algorithm will probably need to be described in the documentation.
