### ISSUE TITLE
Display approximated preferred stock conversion multiplier with an indicator

### ISSUE THREAD

**Issue by daviidy** [captable/ocx#42]
## Scope
In v0.4 of the OCX sample spreadsheet, the Stakeholder Snapshot sheet includes the preferred stock conversion multiplier in the header, to 4 decimal places. However, when the conversion ratio is not a whole number, this value is approximated, and the user needs to be aware of this.

To improve the user experience, we need to update the display logic to indicate when the preferred stock conversion multiplier is approximated. 

## Desired outcome
Display the approximated value with a tilde (~) to signal to the user that the value is not exact. For example, if the conversion ratio is 3 → 8, which is 2 2/3, we will display ~2.6667 in the header.

## To-Do
- [ ] If necessary, determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval, if necessary
- [ ] ocf-package: Are the necessary OCF Files being processed?
- [ ] model: Are the necessary OCF Objects being consumed?
- [ ] Develop workbook against Model interfaces.
- [ ] Implement actual Model
- [ ] Integrate and test end-to-end
