### ISSUE TITLE
Handling conversion of Stock Plans to Preferred Stock

### ISSUE THREAD

**Issue by daviidy** [captable/ocx#43]
## Scope
On the Stakeholder Snapshot sheet, the "Stock Options" columns look like this:
![233648504-785847f2-7ec5-419d-a31d-3ba36554368d](https://github.com/captable/ocx/assets/16840207/10e516df-3a42-4e27-b61d-e416632e19ee)

When a stock plan converts to preferred stock, it is unclear what the behavior should be. One possible interpretation is to seek out the "winning" common stock by following the same algorithm for handling multiple stock class conversion rights for preferred stock classes. This would involve an additional layer in the tree diagram in issue #22, where vested options are converted to the preferred stock and then traversed to determine the "winning" common stock with the lowest non-zero vote count.

## Desired outcome
In the case of conversion, the function used in the stock plan cells needs to show the converted value (actual holdings * ratio). Nothing should change in the header

## To-Do
- [ ] If necessary, determine necessary in-tool calculations and [document](https://docs.google.com/document/d/19iVTJfJxIMr_gQHzMgSAHR6PhCBFEHg0TahjYc8uOac/edit#bookmark=id.elk3tal0dbg) for review and approval, if necessary
- [ ] ocf-package: Are the necessary OCF Files being processed?
- [ ] model: Are the necessary OCF Objects being consumed?
- [ ] Develop workbook against Model interfaces.
- [ ] Implement actual Model
- [ ] Integrate and test end-to-end
